import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 05-Oct-2022 03:55:14 PM'
'File path: C:\\Users\\raymart.bernardo\\Downloads\\ESBO_REVAMP - Part 1 - Login.Final.side'
'Generated by: raymart.bernardo@inplaymatrix.com'
'----------------------------------------------------'

String baseUrl = "https://esimbo-cld-hk-staging.imdgreat.com"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | /login |  | "
selenium.open("/login", "")

"setWindowSize | 1936x1056 |  | "
// Method setWindowSize is not supported

"click | xpath=//div[@id='root']/div/div/div[2]/div/div/div |  | click ddl_Language"
selenium.click("xpath=//div[@id='root']/div/div/div[2]/div/div/div")

"click | xpath=//div[@id='react-select-2-listbox']/div/div |  | select li_English"
selenium.click("xpath=//div[@id='react-select-2-listbox']/div/div")

"verifyElementPresent | xpath=//input[@placeholder='User Name'] |  | verify placeholder text on txt_Username"
verifyTrue(selenium.isElementPresent("xpath=//input[@placeholder='User Name']"))

"verifyElementPresent | xpath=//input[@placeholder='Password'] |  | verify placeholder text on txt_Password"
verifyTrue(selenium.isElementPresent("xpath=//input[@placeholder='Password']"))

"verifyText | xpath=//p | * Password is case-sensitive. | verify warning message"
verifyTrue(selenium.getText("xpath=//p").matches(".* Password is case-sensitive."))

"verifyText | xpath=//button | Login | verify text on btn_Login"
verifyEquals("Login", selenium.getText("xpath=//button"))

"click | xpath=//div[@id='root']/div/div/div[2]/div/div/div |  | click ddl_Language"
selenium.click("xpath=//div[@id='root']/div/div/div[2]/div/div/div")

"click | xpath=//div[@id='react-select-2-listbox']/div/div[2] |  | select li_Chinese"
selenium.click("xpath=//div[@id='react-select-2-listbox']/div/div[2]")

"verifyElementPresent | xpath=//input[@placeholder='用户名'] |  | verify placeholder text on txt_Username"
verifyTrue(selenium.isElementPresent("xpath=//input[@placeholder='用户名']"))

"verifyElementPresent | xpath=//input[@placeholder='密码'] |  | verify placeholder text on txt_Password"
verifyTrue(selenium.isElementPresent("xpath=//input[@placeholder='密码']"))

"verifyText | xpath=//p | * 密码区分大小写。 | verify warning message"
verifyTrue(selenium.getText("xpath=//p").matches(".* 密码区分大小写。"))

"verifyText | xpath=//button | 登录 | verify text on btn_Login"
verifyEquals("登录", selenium.getText("xpath=//button"))

"click | xpath=//div[@id='root']/div/div/div[2]/div/div/div |  | click ddl_Language"
selenium.click("xpath=//div[@id='root']/div/div/div[2]/div/div/div")

"click | xpath=//div[@id='react-select-2-listbox']/div/div[3] |  | select li_Thai"
selenium.click("xpath=//div[@id='react-select-2-listbox']/div/div[3]")

"verifyElementPresent | xpath=//input[@placeholder='ชื่อผู้ใช้งาน'] |  | verify placeholder text on txt_Username"
verifyTrue(selenium.isElementPresent("xpath=//input[@placeholder='ชื่อผู้ใช้งาน']"))

"verifyElementPresent | xpath=//input[@placeholder='รหัสผ่าน'] |  | verify placeholder text on txt_Password"
verifyTrue(selenium.isElementPresent("xpath=//input[@placeholder='รหัสผ่าน']"))

"verifyText | xpath=//p | * รหัสผ่านต้องตรงตามตัวพิมพ์ใหญ่ - เล็ก | verify warning message"
verifyTrue(selenium.getText("xpath=//p").matches(".* รหัสผ่านต้องตรงตามตัวพิมพ์ใหญ่ - เล็ก"))

"verifyText | xpath=//button | ล็อคอิน | verify text on btn_Login"
verifyEquals("ล็อคอิน", selenium.getText("xpath=//button"))
