import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 05-Oct-2022 03:55:00 PM'
'File path: C:\\Users\\raymart.bernardo\\Downloads\\ESBO_REVAMP - Part 1 - Login.Final.side'
'Generated by: raymart.bernardo@inplaymatrix.com'
'----------------------------------------------------'

String baseUrl = "https://esimbo-cld-hk-staging.imdgreat.com"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | / |  | "
selenium.open("/", "")

"click | xpath=//div[@id='root']/div/div/div[5]/div[2] |  | click btn_User menu"
selenium.click("xpath=//div[@id='root']/div/div/div[5]/div[2]")

"click | xpath=//div[@id='root']/div/div/div[6]/div[3]/div/div |  | click btn_Change Password"
selenium.click("xpath=//div[@id='root']/div/div/div[6]/div[3]/div/div")

"verifyText | xpath=//form/div[2]/div[3]/div | รหัสผ่านใหม่ | verify text on lbl_New Password"
verifyEquals("รหัสผ่านใหม่", selenium.getText("xpath=//form/div[2]/div[3]/div"))

"verifyEditable | xpath=//input[@name='newPassword'] |  | verify if txt_New Password is editable"
verifyTrue(selenium.isEditable("xpath=//input[@name='newPassword']"))

"verifyElementPresent | xpath=//input[@placeholder='รหัสผ่านใหม่'] |  | verify text on txt_New Password"
verifyTrue(selenium.isElementPresent("xpath=//input[@placeholder='รหัสผ่านใหม่']"))

"mouseOver | xpath=//input[@name='newPassword'] |  | mouse over txt_New Password"
selenium.mouseOver("xpath=//input[@name='newPassword']")

"click | xpath=//input[@name='newPassword'] |  | click txt_New Password"
selenium.click("xpath=//input[@name='newPassword']")

"click | xpath=//form |  | click outside of the txt_New Password"
selenium.click("xpath=//form")

"verifyText | xpath=//div[2]/div[3]/div[3] | รหัสผ่านใหม่ ต้องไม่เว้นว่าง | verify if 'New Password cannot be blank.' is presented and correct"
verifyEquals("รหัสผ่านใหม่ ต้องไม่เว้นว่าง", selenium.getText("xpath=//div[2]/div[3]/div[3]"))

"type | xpath=//input[@name='newPassword'] | asdf123 | type asdf123 on txt_New Password"
selenium.type("xpath=//input[@name='newPassword']", "asdf123")

"verifyText | xpath=//div[2]/div[3]/div[3] | ต้องมีอักขระอย่างน้อย 8 ตัว | verify if 'Must be at least 8 characters.' is presented and correct."
verifyEquals("ต้องมีอักขระอย่างน้อย 8 ตัว", selenium.getText("xpath=//div[2]/div[3]/div[3]"))

"type | xpath=//input[@name='newPassword'] | ASDF!@#$ | type  ASDF!@#$ on txt_New Password"
selenium.type("xpath=//input[@name='newPassword']", "ASDF!@#$")

"verifyText | xpath=//div[2]/div[3]/div[3] | รหัสผ่านไม่ตรงตามข้อกำหนดของนโยบายรหัสผ่าน | verify if 'The password does not meet the password policy requirements.' is presented and correct."
verifyEquals("รหัสผ่านไม่ตรงตามข้อกำหนดของนโยบายรหัสผ่าน", selenium.getText("xpath=//div[2]/div[3]/div[3]"))

"type | xpath=//input[@name='oldPassword'] | asdf1234 | type asdf1234 on txt_Current Password"
selenium.type("xpath=//input[@name='oldPassword']", "asdf1234")

"type | xpath=//input[@name='newPassword'] | asdf1234 | type asdf1234 on txt_New Password"
selenium.type("xpath=//input[@name='newPassword']", "asdf1234")

"verifyText | xpath=//div[2]/div[3]/div[3] | รหัสผ่านปัจจุบันและรหัสผ่านใหม่ไม่สามารถเหมือนกันได้ | verify if 'Current Password and New Password can’t be the same.' is presented and correct."
verifyEquals("รหัสผ่านปัจจุบันและรหัสผ่านใหม่ไม่สามารถเหมือนกันได้", selenium.getText("xpath=//div[2]/div[3]/div[3]"))
